### ISSUE TITLE
Add a provider for UK Parliament elections

### ISSUE THREAD

**Issue by dedavidson** [localgovdrupal/localgov_elections_reporting#2]
A provider to source UK parliament constituency boundaries within Local Authority areas.

**Comment by dedavidson** [comment]
ONS data sources:

Constituencies Boundaries - https://geoportal.statistics.gov.uk/datasets/ons::westminster-parliamentary-constituencies-future-boundaries-uk-bfe-3/about

Lookup dataset - https://geoportal.statistics.gov.uk/datasets/ons::ward-to-westminster-parliamentary-constituency-to-lad-to-utla-dec-2023-lookup-in-the-uk/about but is PCON23 not PCON24

Have contacted ONS to find timeline for PCON24

**Comment by dedavidson** [comment]
Response from ONS

> We are still processing the latest version of Ordnance Survey Boundary-Line.
>
> We haven’t started on these lookups up yet but they will be updated as soon as possible and published on the Open Geography portal in due course.

**Comment by dedavidson** [comment]
@willguv as you can see above ONS have come back with a not ideal timeline! Given that the mapping between Local Authority and Constituencies is not going to exist in time for us to use it we are proposing to use a name lookup approach. 

The user will type name/partial name and an autocomplete will show potential matches from the ONS Constituencies Boundaries datasource. Once they select the one they want it will be added to a "basket" and they repeat till they have added all the constituencies they need. Once submitted this will then go and retrieve the boundaries.

Thoughts?

**Comment by willguv** [comment]
Hi Duncan, are the ONS boundaries up to date?

If so I think your suggestion is a good idea - councils will know the constituencies they're covering and can look up/ add them

**Comment by dedavidson** [comment]
@willguv yes the dataset at https://geoportal.statistics.gov.uk/datasets/ons::westminster-parliamentary-constituencies-future-boundaries-uk-bfe-3/about is up-to-date

Ok will proceed with development

**Comment by willguv** [comment]
Thanks for the update, looking forward to seeing it 

Got your note about design too - cheers for looping Dave in
