### ISSUE TITLE
Elections: Mobile menu fixes

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections_reporting#43]
Issues identified by Dave Hampton, let's discuss which we can address

The usual issue we encounter with having to scroll past long menus on mobile applies:

![Image](https://github.com/localgovdrupal/localgov_elections_reporting/assets/708140/6fbac1c3-03d9-4e54-8ff4-e067c47fb9cd)

1. We need to ensure screen reader users can skip this menu and jump to content

2. On mobile we can consider adding toggle controls for the menu, examples on other templates, [eg D&G HTML publications](https://www.figma.com/proto/HFdkCuAfwlsyZabrhZQ8Vd/DGC-Website-and-application-guidelines?page-id=0%3A1&node-id=8090-15335&viewport=4157%2C14644%2C1&t=vX2iGq76bDiAMM3n-8&scaling=min-zoom&starting-point-node-id=8090%3A15335&hotspot-hints=0&hide-ui=1)

3. Add focus style to active page

The above could also be addressed by utilising the subsites menu.

**Comment by markconroy** [comment]
PR for this: #75 

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.
