### ISSUE TITLE
Elections: fixes for tables

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections_reporting#44]
Issues identified by Dave Hamilton. I think they're all addressed by removing table styles from Elections, so they use LGD or council defaults. Can you confirm @dedavidson please

For tables like this:

![Image](https://github.com/localgovdrupal/localgov_elections_reporting/assets/708140/6ffe616c-fdae-4fd2-8f68-3814f54791da)

1) I would revert to using simple headings and the simple table styles, no tints or background colours:

normal h2  = Ward results
Table headings = Ward, Party, Candidate

2) I would avoid table sorting on public facing tables, never seen it on GDS and the links / arrows sometimes used in the table headings can be confusing

PR https://github.com/localgovdrupal/localgov_elections_reporting/issues/36

3) For the party labels I would make them all use white text and pick a dark enough background colour for each to pass colour contrast

NOT DOING

> Duncan writes: This is editable via taxonomy so that user can choose text colours and backgrounds that are accessible. There are some party colour i.e. Lib Dems which can't use white text.

**Comment by dedavidson** [comment]
Yes @willguv #39 resolved this.
