### ISSUE TITLE
Elections: Fixes for charts

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections_reporting#45]
Issues identified by Dave Hamilton

For charts like this:

![Image](https://github.com/localgovdrupal/localgov_elections_reporting/assets/708140/5d5ec7c3-23b6-43e4-a8e4-f9e6cf2f6738)

1) I’d make ‘Election summary’ a normal h2 (same as table titles)

Is this done @dedavidson?

2) I would design a wrapper for charts that doesn’t have keylines, so as not to distract from the lines in the chart, for D&G this would most likely be a white box as we can sit them on our grey page background. Other councils may want a tint

Is there a tint color in LGD base we could call @markconroy 

If not, maybe leave this one as it would require councils to make a dev change

**Comment by dedavidson** [comment]
@willguv #39 resolved `<h2>` and also partially the wrapper as it removed the box around the graph. I would suggest leaving for councils to tint as will depend on their theme background colour.
