### ISSUE TITLE
Elections: fixes for electoral map

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections_reporting#46]
Issues identified by Dave Hamilton

https://www.cumberland.gov.uk/node/21483/electoral-map

1) I’d would add a h2 or h3 above the map so it is consistent with the other pages (see above tables, charts)

2) Is there a way we can show a key above or below  the map?

LEAVE TO FUTURE VERSION

3) Does the map need terrain? Don’t think so, a flatter map would work better

FIX IF EASY

4) Does it need some context in the page: ‘Choose an area on the map to see the ward information ’

**Comment by dedavidson** [comment]
@willguv I can quickly do this one.

**Comment by dedavidson** [comment]
#50 has fixes for 1 and 4. 

For 3 having reviewed available base maps, I think the current one is best.
