### ISSUE TITLE
Elections: fixes for share of the vote page

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections_reporting#48]
Issues identified by Dave Hamilton

1. He recommends following the same approach as tables https://github.com/localgovdrupal/localgov_elections_reporting/issues/44

@dedavidson can you confirm this is done as part of the tables changes? Thanks

2. Add emphasis, size and bold on the total Total votes: 120,000

@markconroy could you do this please?

**Comment by dedavidson** [comment]
@willguv yes 1. is fixed by #39
