### ISSUE TITLE
Elections: fixes to electoral candidates page

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_elections_reporting#49]
Issues identified by Dave Hamilton

He recommends following the same approach as tables https://github.com/localgovdrupal/localgov_elections_reporting/issues/44

@dedavidson can you confirm this is done as part of the tables changes? Thanks

Could you add a PDF to https://www.cumberland.gov.uk/node/21483/candidates so I can see how it looks please?

**Comment by dedavidson** [comment]
@willguv #39 fixes table styling. I will add a PDF to a local/dev instance and update here

**Comment by dedavidson** [comment]
This is it within a default LGD install
![image](https://github.com/localgovdrupal/localgov_elections_reporting/assets/5949449/c115a4a1-be2a-46ec-b9b6-0ffd42887cae)

**Comment by willguv** [comment]
Thanks @dedavidson how hard is it to hide the electoral candidates page if no PDFs are uploaded at all?

**Comment by dedavidson** [comment]
I can do a PR tomorrow for that - not difficult

**Comment by willguv** [comment]
Thank you!

**Comment by dedavidson** [comment]
@willguv this is done. @rgcarr is going to review.
