### ISSUE TITLE
Question: Zoom level for Electoral map

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_elections_reporting#53]
Hello,
The default [zoom level](https://github.com/localgovdrupal/localgov_elections_reporting/blob/f10be82663d5a48ff967a8e697120f9676605c0d/config/install/views.view.electoral_map.yml#L415) is appearing too small in the Electoral map.  The [map centre](https://github.com/localgovdrupal/localgov_elections_reporting/blob/f10be82663d5a48ff967a8e697120f9676605c0d/config/install/views.view.electoral_map.yml#L411) is also set in Cumbria.  I had to manually adjust this in the [electoral_map view](https://github.com/localgovdrupal/localgov_elections_reporting/blob/1.x/config/install/views.view.electoral_map.yml) for my location.  Is that the right way to do this or have I missed something?

FOA @chriswales95  @dedavidson @finnlewis

**Comment by dedavidson** [comment]
@Adnan-cds The forcing of the position of the map shouldn't be there. Have removed so that the auto-boxing works.
