### ISSUE TITLE
Missing default opacity when creating party terms.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_elections_reporting#76]
When adding party taxonomy terms for the first time, the party colour field does not have a default value set for the colour opacity.

![image](https://github.com/localgovdrupal/localgov_elections_reporting/assets/326588/7422a27f-f89d-4fe5-8030-ad0a565d758e)

This means we need to explicitly state 1 as the opacity value every time we create a new party term.

Probably makes sense to have this default to 1, like the other colour field.

**Comment by markconroy** [comment]
Closed by #77
